### PR TITLE
Remove uses of `Yuni::Mutex`, use `std::mutex` instead

### PR DESCRIPTION
**Pull request by NicolasSalmieriScalian**

### CODE REVIEW

**Review by flomnes — COMMENTED** [review]
LGTM. We usually don't specify template arguments when they're obvious, from C++17 they're deduced, see [here](https://en.cppreference.com/w/cpp/language/class_template_argument_deduction). We have been using C++17 for over a year, and will soon be using C++20.

```cpp
std::mutex mutex;
std::lock_guard<std::mutex> lock(mutex); // C++03/C++11
std::lock_guard lock(mutex); // C++17
```

**Comment by NicolasSalmieriScalian** [comment]
> LGTM. We usually don't specify template arguments when they're obvious, from C++17 they're deduced, see [here](https://en.cppreference.com/w/cpp/language/class_template_argument_deduction). We have been using C++17 for over a year, and will soon be using C++20.
> 
> ```c++
> std::mutex mutex;
> std::lock_guard<std::mutex> lock(mutex); // C++03/C++11
> std::lock_guard lock(mutex); // C++17
> ```

Should I remove all obvious template arguments of std::lock_guard in the codebase, or just those I added?

**Comment by flomnes** [comment]
> Should I remove all obvious template arguments of std::lock_guard in the codebase, or just those I added?

Can you please remove them all ?

**Comment by a-zakir** [comment]
> > LGTM. We usually don't specify template arguments when they're obvious, from C++17 they're deduced, see [here](https://en.cppreference.com/w/cpp/language/class_template_argument_deduction). We have been using C++17 for over a year, and will soon be using C++20.
> > ```c++
> > std::mutex mutex;
> > std::lock_guard<std::mutex> lock(mutex); // C++03/C++11
> > std::lock_guard lock(mutex); // C++17
> > ```
> 
> Should I remove all obvious template arguments of std::lock_guard in the codebase, or just those I added?



> > LGTM. We usually don't specify template arguments when they're obvious, from C++17 they're deduced, see [here](https://en.cppreference.com/w/cpp/language/class_template_argument_deduction). We have been using C++17 for over a year, and will soon be using C++20.
> > ```c++
> > std::mutex mutex;
> > std::lock_guard<std::mutex> lock(mutex); // C++03/C++11
> > std::lock_guard lock(mutex); // C++17
> > ```
> 
> Should I remove all obvious template arguments of std::lock_guard in the codebase, or just those I added?

you named this Pr "Remove uses of Yuni::Mutex, use std::mutex instead " should i....

**Comment by flomnes** [comment]
Hi @NicolasSalmieriScalian, can you please resolve conflicts ? Our license has switched to MPL 2.0, allowing us to merge PRs from you

**Comment by flomnes** [comment]
See #1964

**Pull request closed without merging**
