### PR TITLE
[DEV] Ini files load encapsulation

### PR DESCRIPTION
**Pull request by kathvargasr**
First step of encapsulation, following the node diagram of [the dependency graph executor for study loading](https://gopro-collaboratif.rte-france.com/display/ANTR/Refactoring+Antares%27+Study+Loader)

### CODE REVIEW

**Review by flomnes — CHANGES_REQUESTED** [review]
`Statistics::LogsDumper statisticsDumper` was removed. It displayed a log notice

```cpp
void DumpToLogs()
{
    Yuni::MutexLocker locker(gMutex);
    logs.info() << "[statistics] disk: read: " << (gReadFromDisk / 1024)
                << " ko, written: " << (gWrittenToDisk / 1024) << " ko";
    logs.info() << "[statistics] network: read: " << (gReadFromNetwork / 1024)
                << " ko, written: " << (gWrittenToNetwork / 1024) << " ko";
}
```
Is this intended ?

Please apply `clang-format`

**Comment by guilpier-code** [comment]
Sorry, I don't see observe the removal you mentioned. Am i missing something ?

**Review by guilpier-code — APPROVED** [review]

**Comment by JasonMarechal25** [comment]
@guilpier-code 
 PR Was closed. Was it voluntary ?

**Comment by flomnes** [comment]
> @guilpier-code PR Was closed. Was it voluntary ?

I think it was a mistake

**Review by flomnes — APPROVED** [review]

**Pull request merged**
