### PR TITLE
python warnings

### PR DESCRIPTION
**Pull request by a-zakir**
Few changes, a lot of clarity

### CODE REVIEW

**Review by flomnes — COMMENTED** [review]
Do we really need to downgrade ?

**Comment by a-zakir** [comment]
> Do we really need to downgrade ?

No,
there is just a warning in a case of test failure [see](https://github.com/AntaresSimulatorTeam/Antares_Simulator/actions/runs/7184564424/job/19565904276)

**Comment by sylvlecl** [comment]
Lots of people seem to be waiting for the fix release of this warning by dateutil maintainers ^^
See https://github.com/dateutil/dateutil/issues/1284  and https://github.com/dateutil/dateutil/issues/1314

**Comment by flomnes** [comment]
This warning is non-blocking. Python people will fix it...someday. No need to downgrade for this.

**Pull request closed without merging**
